# Path to dataset (relative to where you run the script)
path: ../dataset

# Paths to train and val images
train: ../images/train
val: ../images/val

# Number of classes
nc: 3

# Class names
names:
  0: Garlic Bulb
  1: Garlic Root
  2: Gripper